"""empty message

Revision ID: 149bb84ad00f
Revises: 6afd45a53500
Create Date: 2025-10-29 11:26:30.365243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149bb84ad00f'
down_revision = '6afd45a53500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('personality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog')
    # ### end Alembic commands ###
